### ISSUE TITLE
你好，请问我怎样才能让班级名称出现？

### ISSUE THREAD

**Issue by MfonobongIme** [Kazuhito00/yolox-bytetrack-sample#2]
你好，请问我怎样才能让班级名称出现？

**Comment by Kazuhito00** [comment]
这个Repository是一个单一的班级ByteTrack
如果要显示类名，请使用以下Repository
https://github.com/Kazuhito00/yolox-bytetrack-mcmot-sample

**Comment by MfonobongIme** [comment]
非常感谢！有效
